import { FormEvent, useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { Settings } from "./components/Settings";
import { RoomSocket } from "./services/socket";
import { VoiceMesh } from "./services/voice";
import { peerVolumes } from "./services/storage";
import type { ChatMessage, ConnectionState, RoomUser, ServerEvent } from "./types/protocol";
const constraints: MediaTrackConstraints = { echoCancellation: true, noiseSuppression: true, autoGainControl: true };
export default function App() { const [stage, setStage] = useState<"welcome"|"room">("welcome"); const [join, setJoin] = useState(false); const [name, setName] = useState(""); const [roomName, setRoomName] = useState("My Room"); const [endpoint, setEndpoint] = useState("ws://100.x.x.x:43210/ws"); const [password, setPassword] = useState(""); const [messages, setMessages] = useState<ChatMessage[]>([]); const [users, setUsers] = useState<RoomUser[]>([]); const [me, setMe] = useState(""); const [state, setState] = useState<ConnectionState>("offline"); const [draft, setDraft] = useState(""); const [typing, setTyping] = useState(""); const [settings, setSettings] = useState(false); const [voice, setVoice] = useState(false); const [muted, setMuted] = useState(false); const [deaf, setDeaf] = useState(false); const socket = useRef<RoomSocket | null>(null); const mesh = useRef<VoiceMesh | null>(null); const last = useRef<HTMLDivElement>(null);
 const event = (e: ServerEvent) => { if (e.type === "ready") { setMe(e.userId); setMessages(e.messages); setUsers(e.users); socket.current?.send({ type: "authenticate", username: name, password }); } if (e.type === "message:create") setMessages((x) => [...x, e.message]); if (e.type === "message:update") setMessages((x) => x.map((m) => m.id === e.message.id ? e.message : m)); if (e.type === "message:delete") setMessages((x) => x.filter((m) => m.id !== e.id)); if (e.type === "presence") setUsers(e.users); if (e.type === "typing") setTyping(e.active ? `${e.name} is typing…` : ""); if (e.type === "signal") void mesh.current?.receive(e.from, e.data); if (e.type === "error") alert(e.message); };
 const connect = async (ev: FormEvent) => { ev.preventDefault(); if (!name.trim() || name.trim().length < 2) return; let address = endpoint; if (!join) { try { address = await invoke<string>("start_host", { roomName, username: name.trim(), password, port: 43210 }); } catch (error) { alert(`Could not start host: ${String(error)}`); return; } } const s = new RoomSocket(address, event, setState); socket.current = s; s.connect(); setStage("room"); setTimeout(() => s.send({ type: "authenticate", username: name.trim(), password }), 250); };
 useEffect(() => { last.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]); useEffect(() => () => { socket.current?.close(); mesh.current?.close(); }, []);
 const send = (ev: FormEvent) => { ev.preventDefault(); if (draft.trim()) socket.current?.send({ type: "message:create", content: draft.trim() }); setDraft(""); socket.current?.send({ type: "typing", active: false }); };
 const toggleVoice = async () => { if (voice) { mesh.current?.close(); mesh.current = undefined; setVoice(false); socket.current?.send({ type:"voice:state", joined:false, muted }); return; } const m = new VoiceMesh((to,data) => socket.current?.send({type:"signal",to,data}), () => undefined); try { await m.start(constraints); mesh.current=m; setVoice(true); socket.current?.send({type:"voice:state",joined:true,muted:false}); users.filter((u)=>u.inVoice && u.id !== me).forEach((u)=>void m.call(u.id)); } catch { alert("Microphone permission is required to join voice."); } };
 if(stage === "welcome") return <main className="welcome"><div className="brand">HUSH <span>PRIVATE VOICE</span></div><h1>{join ? "Join a private room" : "Start a private room"}</h1><p>Direct room communication over your private VPN network.</p><form onSubmit={connect}><label>{join ? "Invite address" : "Host address"}<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="ws://100.x.x.x:43210/ws"/></label>{!join && <label>Room name<input value={roomName} onChange={e=>setRoomName(e.target.value)} required maxLength={64}/></label>}<label>Your username<input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={32} required/></label><label>Room password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>{join ? "Join room" : "Create & host room"}</button></form><button className="link" onClick={()=>setJoin(!join)}>{join ? "Create a room instead" : "Join an existing room"}</button></main>;
 return <main className="app"><header><b>Private Room</b><span className={state}>● {state === "connected" ? "Connected" : state === "reconnecting" ? "Reconnecting…" : "Offline"}</span></header><aside className="sidebar"><small>TEXT</small><button className="channel active"># general</button><small>VOICE</small><button className={voice ? "channel voice joined" : "channel voice"} onClick={()=>void toggleVoice()}>◉ General <em>{voice ? "Connected" : "Join"}</em></button><div className="profile"><b>{name}</b><div><button onClick={()=>{setMuted(!muted); mesh.current?.setMuted(!muted); socket.current?.send({type:"voice:state",joined:voice,muted:!muted})}}>{muted ? "🔇" : "🎤"}</button><button onClick={()=>{setDeaf(!deaf); document.querySelectorAll("audio").forEach(a=>a.muted=!deaf)}}>{deaf ? "🔇" : "🔊"}</button><button onClick={()=>setSettings(true)}>⚙</button></div></div></aside><section className="chat"><div className="chathead"><b># general</b><span>{typing}</span></div><div className="messages">{messages.map(m=><article key={m.id}><b>{m.authorName}</b><time>{new Date(m.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time><p>{m.content}</p>{m.authorId===me && <span><button onClick={()=>{const content=prompt("Edit message",m.content); if(content) socket.current?.send({type:"message:update",id:m.id,content})}}>Edit</button><button onClick={()=>socket.current?.send({type:"message:delete",id:m.id})}>Delete</button></span>}</article>)}<div ref={last}/></div><form className="composer" onSubmit={send}><input value={draft} onChange={e=>{setDraft(e.target.value);socket.current?.send({type:"typing",active:true})}} placeholder="Write a message…" maxLength={4000}/><button>Send ↗</button></form></section><aside className="members"><small>ONLINE — {users.length}</small>{users.map(u=><div className="member" key={u.id}><i>●</i><div><b>{u.name}</b><span>{u.inVoice ? (u.muted ? "🔇 Muted" : u.speaking ? "◉ Speaking" : "🎤 In General") : "Online"}</span>{u.id !== me && <label>Volume <input type="range" min="0" max="150" defaultValue={peerVolumes.get()[u.id] ?? 100} onChange={e=>{peerVolumes.set(u.id,+e.target.value);mesh.current?.setPeerVolume(u.id,+e.target.value)}}/></label>}</div></div>)}</aside>{settings&&<Settings onClose={()=>setSettings(false)}/>}</main> }
